from typing import Dict, Any
import pandas as pd
from openai import OpenAI

client = OpenAI()


def build_soc_summary(results: Dict[str, Any], lang: str = "es") -> str:
    """
    Build a high-level text digest from the detection results.

    Parameters
    results : Dict[str, Any]
        Dictionary with detection results. Expected keys:
        - "bruteforce"
        - "successful_bruteforce"
        - "port_scan"
        - "off_hours"
        - "password_spraying"
    lang : str, optional
        Language code: "es" or "en" Defaults to "es"
    """

    lines: list[str] = []

    if lang == "en":
        lines.append("SOC detections summary generated by the analysis engine.\n")
    else:
        lines.append("Resumen de detecciones SOC generado por el motor de análisis.\n")

    # bruteforce
    df_bf = results.get("bruteforce")
    if df_bf is not None and not df_bf.empty:
        lines.append("Brute force:")
        if lang == "en":
            lines.append(f"- Suspicious IPs: {df_bf.shape[0]}")
        else:
            lines.append(f"- IPs sospechosas: {df_bf.shape[0]}")

        if {"source_ip", "failures"} <= set(df_bf.columns):
            top_bf = df_bf.sort_values("failures", ascending=False).head(5)
            for _, row in top_bf.iterrows():
                if lang == "en":
                    lines.append(
                        f"  • IP {row['source_ip']} with {row['failures']} failed attempts"
                    )
                else:
                    lines.append(
                        f"  • IP {row['source_ip']} con {row['failures']} intentos fallidos"
                    )
        lines.append("")

    # successful bruteforce
    df_sbf = results.get("successful_bruteforce")
    if df_sbf is not None and not df_sbf.empty:
        lines.append("Successful brute force:")
        if lang == "en":
            lines.append(f"- Possible compromised accounts: {df_sbf.shape[0]}")
        else:
            lines.append(f"- Posibles cuentas comprometidas: {df_sbf.shape[0]}")

        for _, row in df_sbf.head(5).iterrows():
            ip = row.get("source_ip", "unknown" if lang == "en" else "desconocida")
            user = row.get("username", "unknown" if lang == "en" else "desconocido")
            fails = row.get("failures", "N/A")
            if lang == "en":
                lines.append(
                    f"  • IP {ip} targeting user {user} after {fails} failed attempts"
                )
            else:
                lines.append(
                    f"  • IP {ip} contra usuario {user} tras {fails} intentos fallidos"
                )
        lines.append("")

    # portscan
    df_ps = results.get("port_scan")
    if df_ps is not None and not df_ps.empty:
        lines.append("Portscan:")
        if lang == "en":
            lines.append(
                f"- IPs with port-scanning behavior: {df_ps.shape[0]}"
            )
        else:
            lines.append(
                f"- IPs con comportamiento de escaneo de puertos: {df_ps.shape[0]}"
            )

        col_targets = "dest_port" 
        if {"source_ip", col_targets} <= set(df_ps.columns):
            top_ps = df_ps.sort_values(col_targets, ascending=False).head(5)
            for _, row in top_ps.iterrows():
                if lang == "en":
                    lines.append(
                        f"  • IP {row['source_ip']} reached {row[col_targets]} different ports/targets"
                    )
                else:
                    lines.append(
                        f"  • IP {row['source_ip']} alcanzó {row[col_targets]} puertos/targets distintos"
                    )
        lines.append("")

    # off-hours login
    df_off = results.get("off_hours")
    if df_off is not None and not df_off.empty:
        lines.append("Off-hours logins:")
        if lang == "en":
            lines.append(
                f"- Logins detected outside normal hours: {df_off.shape[0]}"
            )
        else:
            lines.append(
                f"- Inicios de sesión fuera de horario detectados: {df_off.shape[0]}"
            )

        if {"username", "timestamp"} <= set(df_off.columns):
            for _, row in df_off.head(5).iterrows():
                user = row.get("username", "unknown" if lang == "en" else "desconocido")
                ts = row.get("timestamp", "no_timestamp" if lang == "en" else "sin_timestamp")
                if lang == "en":
                    lines.append(
                        f"  • User {user} with off-hours login at {ts}"
                    )
                else:
                    lines.append(
                        f"  • Usuario {user} con login fuera de horario en {ts}"
                    )
        lines.append("")

    # password spraying
    df_spr = results.get("password_spraying")
    if df_spr is not None and not df_spr.empty:
        lines.append("Password spraying:")
        if lang == "en":
            lines.append(
                f"- IPs with password spraying pattern: {df_spr.shape[0]}"
            )
        else:
            lines.append(
                f"- IPs con patrón de password spraying: {df_spr.shape[0]}"
            )

        
        col_users = "unique_users"
        if {"source_ip", col_users} <= set(df_spr.columns):
            for _, row in df_spr.head(5).iterrows():
                if lang == "en":
                    lines.append(
                        f"  • IP {row['source_ip']} tried to authenticate against "
                        f"{row[col_users]} different users"
                    )
                else:
                    lines.append(
                        f"  • IP {row['source_ip']} intentó autenticarse contra "
                        f"{row[col_users]} usuarios distintos"
                    )
        lines.append("")

    # no detections
    if len(lines) == 1:
        if lang == "en":
            lines.append("No suspicious events were detected in this log set.")
        else:
            lines.append("No se detectaron eventos sospechosos en este conjunto de logs.")

    return "\n".join(lines)

def ask_soc_copilot(summary_text: str, lang: str = "es") -> str:
    """
    Send the summary to the OpenAI model and return a structured SOC analysis
    to be displayed in the dashboard.

    Parameters
    ----------
    summary_text : str
        Text summary produced by build_soc_summary.
    lang : str, optional
        Language code: "es" or "en". Defaults to "es".
    """

    if not summary_text or summary_text.strip() == "":
        return (
            "No se proporcionó ningún resumen para analizar."
            if lang == "es"
            else "No summary was provided for analysis."
        )

    if lang == "en":
        system_prompt = (
            "You are a senior SOC analyst. I will give you a summary of detections "
            "from a log analysis engine (brute force, successful brute force, "
            "portscan, off-hours logins and password spraying). "
            "You must ALWAYS respond in English, with a clear, structured report "
            "for a cybersecurity team.\n\n"
            "Response structure:\n"
            "1. Executive summary (non-technical, for leadership)\n"
            "2. Technical details by detection type\n"
            "3. MITRE ATT&CK mapping (relevant technique IDs and names)\n"
            "4. Hypotheses about the attack or possible campaigns\n"
            "5. Concrete IR (incident response) and hardening recommendations\n"
        )

        user_prompt = (
            "Below is the detections summary generated by the engine:\n\n"
            f"{summary_text}\n\n"
            "Generate the report following the specified structure."
        )
    else:
        system_prompt = (
            "Eres un analista SOC senior. Te pasaré un resumen de detecciones "
            "de un motor de análisis de logs (brute force, successful brute force, "
            "portscan, inicios de sesión fuera de horario y password spraying). "
            "Debes responder SIEMPRE en español, con un informe estructurado y claro "
            "para un equipo de ciberseguridad.\n\n"
            "Estructura de la respuesta:\n"
            "1. Resumen ejecutivo (no técnico, orientado a liderazgo)\n"
            "2. Detalles técnicos por tipo de detección\n"
            "3. Mapeo a MITRE ATT&CK (IDs y nombres de técnicas relevantes)\n"
            "4. Hipótesis sobre el ataque o campañas posibles\n"
            "5. Recomendaciones concretas de respuesta (IR) y hardening\n"
        )

        user_prompt = (
            "A continuación está el resumen de detecciones generado por el motor:\n\n"
            f"{summary_text}\n\n"
            "Genera el informe siguiendo la estructura indicada."
        )

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        max_output_tokens=900,
    )

    try:
        content = response.output[0].content[0].text
    except Exception:
        content = (
            "No se pudo extraer la respuesta del modelo. "
            "Revisa la configuración de la API o los logs."
            if lang == "es"
            else "Could not extract the model response. "
                 "Check the API configuration or logs."
        )

    return content